CREATE TABLE JOB(JOB_ID VARCHAR2(15),JOB_TITLE VARCHAR2(30),MIN_SAL NUMBER(7,2),MAX_SAL NUMBER(7,2)); 
INSERT INTO JOB(JOB_ID,JOB_TITLE,MIN_SAL,MAX_SAL) VALUES('IT_PROG','Programmer','4000','10000');
INSERT INTO JOB(JOB_ID,JOB_TITLE,MIN_SAL,MAX_SAL) VALUES('MK_MGR','Marketing manager','9000','15000');
INSERT INTO JOB(JOB_ID,JOB_TITLE,MIN_SAL,MAX_SAL) VALUES('FI_MGR','Finance Manager',8200,'12000');
INSERT INTO JOB(JOB_ID,JOB_TITLE,MIN_SAL,MAX_SAL) VALUES('FI_ACC','Account','4200','9000');
INSERT INTO JOB(JOB_ID,JOB_TITLE,MIN_SAL,MAX_SAL) VALUES('LEC','Lecture','6000','17000');
INSERT INTO JOB(JOB_ID,JOB_TITLE,MIN_SAL,MAX_SAL) VALUES('COMP_OP','Computer Operator','1500','3000');


CREATE TABLE EMPLOYEE (EMP_NO NUMBER(3),EMP_NAME VARCHAR2(30),EMP_SAL NUMBER(8,2),EMP_COMM NUMBER(6,1),DEPT_NO NUMBER(3));
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES('101','Smith','800','NULL','20');
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES('102','Snehal','1600','300','25');
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES('103','Adama','1100','0','20');
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES('104','Aman','3000','NULL','15');
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES('105','Anita','5000','50000','10');
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES('106','Sneha','2450','24500','10');
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES('107','Anamika','2975','NULL','30');


CREATE TABLE DEPOSIT(A_NO VARCHAR2(5),CNAME VARCHAR2(15),BNAME VARCHAR2(10),AMOUNT NUMBER(7,2),A_DATE DATE);
INSERT INTO DEPOSIT(A_NO,CNAME,BNAME,AMOUNT,A_DATE) VALUES ('101','ANIL','ANDHERI','7000','01-JAN-06');
INSERT INTO DEPOSIT(A_NO,CNAME,BNAME,AMOUNT,A_DATE) VALUES ('102','SUNIL','VIRAR','5000','15-JUL-06');
INSERT INTO DEPOSIT(A_NO,CNAME,BNAME,AMOUNT,A_DATE) VALUES ('103','JAY','VILLEPARLE','6500','15-MAR-06');
INSERT INTO DEPOSIT(A_NO,CNAME,BNAME,AMOUNT,A_DATE) VALUES ('104','VIJAY','ANDHERI','8000','17-SEPT-06');
INSERT INTO DEPOSIT(A_NO,CNAME,BNAME,AMOUNT,A_DATE) VALUES ('105','KEYUR','DADAR','7500','19-NOV-06');
INSERT INTO DEPOSIT(A_NO,CNAME,BNAME,AMOUNT,A_DATE) VALUES ('106','MAYUR','BORIVALI','5500','21-DEC-06');


SELECT * FROM EMPLOYEE;. 
SELECT * FROM JOB;
SELECT * FROM DEPOSIT;
SELECT A_NO,AMOUNT FROM DEPOSIT WHERE A_DATE BETWEEN '01-JAN-06' AND '25-JUL-06';
SELECT JOB_ID,JOB_TITLE FROM JOB WHERE MIN_SAL.4000;
SELECT EMP_NAME,EMP_SAL FROM EMPLOYEE WHERE DEP_NO BETWEEN '10' AND '20';
    
SELECT EMP_NAME FROM EMPLOYEE WHERE EMP_NAME LIKE 'A_a%';
SELECT EMP_NAME,EMP_NO,EMP_SAL FROM EMPLOYEE WHERE EMP_NAME LIKE 'Ani__';
SELECT EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO FROM EMPLOYEE LIKE '_n___' AND EMP_COMM IS NOT NULL;
SELECT EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO FROM EMPLOYEE WHERE EMP_NAME LIKE '__a%' AND EMP_COMM IS NULL;
SELECT EMP_NO FROM EMPLOYEE WHERE EMP_NAME LIKE '%\_%' ESCAPE '\';
